### ISSUE TITLE
Registering via Standard Notes client (v3.5.11) fails with "No password cost provided"

### ISSUE THREAD

**Issue by vszakats** [mdouchement/standardfile#44]
Commenting this condition from the server code eliminates the error and results in a seemingly working account:
https://github.com/mdouchement/standardfile/blob/22dfcd510aece919dad8d9d0ea764af323cc9cd2/internal/server/auth_handlers.go#L75-L77

**Comment by mdouchement** [comment]
It's because `v3.5.x` was released too early by mistake and it uses partially the `004` protocol spec which is not supported by the current server released version (v0.5.1).

I'm currently working on the upcoming `004` version which is currently in beta and be released in early 2021 by the standardnotes' team.
https://github.com/mdouchement/standardfile/tree/20200115-004

We just have to wait for the official release.

**Comment by vszakats** [comment]
@mdouchement Thank you for your quick info and no worries about this, I'm good for the time being. And in any case: Thanks for this nice piece of software.
