### ISSUE TITLE
Add clarification on JWT and PASETO parameters in config file

### ISSUE THREAD

**Issue by valantur** [mdouchement/standardfile#70]
Hi, I'm sorry to open an issue request about this because this isn't really an issue... it's just that it's unclear to me whether I should change any of the JWT and PASETO parameters on the standardfile.yml file before deploying the server.
I couldn't find a wiki for this project or any other documentation, so my apologies in advance if it's all explained somewhere else.

Thanks!

**Comment by mdouchement** [comment]
Hello, no worries.
JWT token is the old authentication système.
Since the API version `20200115` (latest) and protocol version `004` (latest), Standard Notes uses the session mechanism.
Within the session object, the `access_token` and `refresh_token` are generated with PASETO.

This project is following the [Standard Notes](https://github.com/standardnotes/) specification.
