### ISSUE TITLE
Is your implementation still up-to-date with the latest StandardNotes changes?

### ISSUE THREAD

**Issue by 1fexd** [mdouchement/standardfile#98]

**Comment by mdouchement** [comment]
The base features are working with the latest client. There are some minor issues like #87 due to an hidden change from the official client. Or #94 due to some mystic issues.

Several features are not implemented:
- Note revision
- File storage
- and some that I don't know

Since it takes time to implement and follow the official evolutions and that I don't need the extra features developed in the offical project (I just need encrypted notes), I won't implement them. I will gladly review PRs implementing the missing features.

My goal is to maintain this project for the main features proposed by the official project. On its own it already takes hours to figure out what is the issue when bug happens (e.g. #87).
